name: app_crescimento
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  pdf: ^3.10.7
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true